--- #YAML:1.0
name:                Devel-GlobalDestruction
version:             0.02
abstract:            ~
license:             ~
author:              ~
generated_by:        ExtUtils::MakeMaker version 6.44
distribution_type:   module
requires:     
    Scope::Guard:                  0
    Sub::Exporter:                 0
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.3.html
    version: 1.3
