--- #YAML:1.0
name:               Test-NoWarnings
version:            1.01
abstract:           Make sure you didn't emit any warnings while testing
author:
    - Fergal Daly <fergal@esatclear.ie>
license:            lgpl
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    perl:           5.006
    Test::Builder:  0.86
    Test::More:     0.47
    Test::Tester:   0.107
resources:
    repository:  http://svn.ali.as/cpan/trunk/Config-Tiny
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.50
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
