---
abstract: ~
author:
  - 'Ash Berlin <ash@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: 6.42
  FindBin: 0
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 0.91'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Class-C3-Componentised
no_index:
  directory:
    - inc
    - t
requires:
  Carp: 0
  Class::C3: 0.20
  Class::Inspector: 0
  MRO::Compat: 0
  Test::Exception: 0
resources:
  license: http://dev.perl.org/licenses/
version: 1.0006
