--- #YAML:1.0
name: Digest-SHA
version: 5.45
abstract: Perl extension for SHA-1/224/256/384/512
license: perl
author:
  - Mark Shelor, mshelor@cpan.org
meta-spec:
  version: 1.3
  url: http://module-build.sourceforge.net/META-spec-v1.3.html
generated_by: Mark Shelor
