---
name: version
version: 0.56
author: ~
abstract: ~
license: perl
requires:
  perl: '> 5.005, !=5.9.1, !=5.9.2'
dynamic_config: 1
provides:
  version:
    file: lib/version.pm
    version: 0.56
  version::vxs:
    file: vutil/vxs.pm
    version: 0.55
generated_by: Module::Build version 0.2611
