# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Class-Accessor
version:      0.30
version_from: lib/Class/Accessor.pm
installdirs:  site
requires:
    base:                          1.01

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.30_01
