--- #YAML:1.0
name:               ExtUtils-MakeMaker
version:            6.56
abstract:           Create a module Makefile
author:
    - Michael G Schwern <schwern@pobox.com>
license:            perl
distribution_type:  module
configure_requires:  {}
build_requires:
    Data::Dumper:  0
requires:
    DirHandle:       0
    File::Basename:  0
    File::Spec:      0.8
    perl:            5.006
    Pod::Man:        0
resources:
    bugtracker:   http://rt.cpan.org/NoAuth/Bugs.html?Dist=ExtUtils-MakeMaker
    homepage:     http://makemaker.org
    license:      http://dev.perl.org/licenses/
    MailingList:  makemaker@perl.org
    repository:   http://github.com/schwern/extutils-makemaker
no_index:
    directory:
        - t
        - inc
    package:
        - DynaLoader
        - in
generated_by:       ExtUtils::MakeMaker version 6.56
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
