---
name: Class-Data-Accessor
version: 0.03
author: ~
abstract: 'Inheritable, overridable class and instance data accessor creation'
license: perl
requires:
  Carp: 0
provides:
  Class::Data::Accessor:
    file: lib/Class/Data/Accessor.pm
    version: 0.03
generated_by: Module::Build version 0.26
