--- #YAML:1.0
name: DateTime-Format-Builder
version: 0.7802
author:
  - ~
abstract: ~
license: perl
requires:
  DateTime: 0.12
  DateTime::Format::Strptime: 1.04
  Params::Validate: 0.72
provides:
  DateTime::Format::Builder:
    file: lib/DateTime/Format/Builder.pm
    version: 0.7802
  DateTime::Format::Builder::Parser:
    file: lib/DateTime/Format/Builder/Parser.pm
    version: 0.77
  DateTime::Format::Builder::Parser::Dispatch:
    file: lib/DateTime/Format/Builder/Parser/Dispatch.pm
    version: 0.78
  DateTime::Format::Builder::Parser::Quick:
    file: lib/DateTime/Format/Builder/Parser/Quick.pm
    version: 0.77
  DateTime::Format::Builder::Parser::Regex:
    file: lib/DateTime/Format/Builder/Parser/Regex.pm
    version: 0.77
  DateTime::Format::Builder::Parser::Strptime:
    file: lib/DateTime/Format/Builder/Parser/Strptime.pm
    version: 0.77
  DateTime::Format::Builder::Parser::generic:
    file: lib/DateTime/Format/Builder/Parser/generic.pm
    version: 0.77
generated_by: Module::Build version 0.23
