---
name: Path-Class
version: 0.18
author:
  - 'Ken Williams, KWILLIAMS@cpan.org'
abstract: Cross-platform path specification manipulation
license: perl
resources:
  bugtracker: http://rt.cpan.org/Public/Dist/Display.html?Name=Path-Class
  homepage: http://code.google.com/p/perl-path-class
  license: http://dev.perl.org/licenses/
  repository: http://perl-path-class.googlecode.com/svn/trunk
build_requires:
  File::Temp: 0
  Test::More: 0
requires:
  Cwd: 0
  File::Path: 0
  File::Spec: 0.87
  File::Spec::Mac: 1.3
  File::stat: 0
  IO::Dir: 0
  IO::File: 0
  overload: 0
configure_requires:
  Module::Build: 0.34
provides:
  Path::Class:
    file: lib/Path/Class.pm
    version: 0.18
  Path::Class::Dir:
    file: lib/Path/Class/Dir.pm
    version: 0.18
  Path::Class::Entity:
    file: lib/Path/Class/Entity.pm
    version: 0.18
  Path::Class::File:
    file: lib/Path/Class/File.pm
    version: 0.18
generated_by: Module::Build version 0.34
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
