---
name: Algorithm-C3
version: 0.06
author:
  - 'Stevan Little, E<lt>stevan@iinteractive.comE<gt>'
  - 'Brandon L. Black, E<lt>blblack@gmail.comE<gt>'
abstract: A module for merging hierarchies using the C3 algorithm
license: perl
resources:
  license: http://dev.perl.org/licenses/
requires:
  Carp: 0.01
build_requires:
  Test::More: 0.47
provides:
  Algorithm::C3:
    file: lib/Algorithm/C3.pm
    version: 0.06
generated_by: Module::Build version 0.2805
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
