--- #YAML:1.0
name:               DBD-SQLite
version:            1.29
abstract:           Self Contained SQLite RDBMS in a DBI Driver
author:
    - Adam Kennedy <adamk@cpan.org>
license:            perl
distribution_type:  module
configure_requires:
    DBI:                  1.57
    ExtUtils::MakeMaker:  6.48
    File::Spec:           0.82
build_requires:
    File::Spec:  0.82
    Test::More:  0.42
requires:
    DBI:        1.57
    Tie::Hash:  0
resources:
    bugtracker:   http://rt.cpan.org/Public/Dist/Display.html?Name=DBD-SQLite
    license:      http://dev.perl.org/licenses/
    MailingList:  http://lists.scsys.co.uk/cgi-bin/mailman/listinfo/dbd-sqlite
    repository:   http://svn.ali.as/cpan/trunk/DBD-SQLite
no_index:
    directory:
        - t
        - inc
        - util
generated_by:       ExtUtils::MakeMaker version 6.50
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
