---
abstract: 'Inheritable, overridable class and instance data accessor creation'
author:
  - 'Based on the creative stylings of Damian Conway, Michael G Schwern,'
distribution_type: module
generated_by: 'Module::Install version 0.77'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Class-Data-Accessor
no_index:
  directory:
    - inc
    - t
requires:
  Carp: 0
  perl: 5.6.1
resources:
  license: http://dev.perl.org/licenses/
version: 0.04004
