--- #YAML:1.0
name:               Sub-Install
version:            0.925
abstract:           install subroutines into packages easily
author:
    - Ricardo Signes <rjbs@cpan.org>
license:            perl
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
requires:
    Scalar::Util:  0
    Test::More:    0
resources:
    Repository:  http://github.com/rjbs/sub-install
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.48
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
