# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         SQL-Abstract-Limit
version:      0.141
version_from: lib/SQL/Abstract/Limit.pm
installdirs:  site
requires:
    Data::Dumper:                  0
    DBI:                           0
    Scalar::Util:                  0
    SQL::Abstract:                 1.2
    Test::Builder:                 0
    Test::Deep:                    0
    Test::Exception:               0
    Test::More:                    0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
