---
abstract: 'Lets you build groups of accessors'
author:
  - 'Matt S. Trout <mst@shadowcatsystems.co.uk>'
build_requires:
  ExtUtils::MakeMaker: 6.42
  Sub::Identify: 0
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 0.91'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Class-Accessor-Grouped
no_index:
  directory:
    - inc
    - t
provides:
  Class::Accessor::Grouped:
    file: lib/Class/Accessor/Grouped.pm
    version: 0.09002
requires:
  Carp: 0
  Class::Inspector: 0
  MRO::Compat: 0
  Scalar::Util: 0
  Sub::Name: 0.04
  perl: 5.6.1
resources:
  license: http://dev.perl.org/licenses/
  repository: http://dev.catalyst.perl.org/repos/bast/trunk/Class-Accessor-Grouped/
version: 0.09002
