---
abstract: 'LDAP client library'
author:
  - 'Graham Barr <gbarr@cpan.org>'
distribution_type: module
generated_by: 'Module::Install version 0.710'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.3.html
  version: 1.3
module_name: Net::LDAP
name: perl-ldap
no_index:
  directory:
    - inc
    - t
requires:
  Convert::ASN1: 0.07
  perl: 5.004
version: 0.35
