--- #YAML:1.0
name: Class-Accessor-Chained
version: 0.01
license: perl
distribution_type: module
requires:
  Class::Accessor: 0
recommends: {}
build_requires:
  Test::More: 0
conflicts: {}
provides:
  Class::Accessor::Chained:
    file: lib/Class/Accessor/Chained.pm
    version: 0.01
  Class::Accessor::Chained::Fast:
    file: lib/Class/Accessor/Chained/Fast.pm
generated_by: Module::Build version 0.21
