--- #YAML:1.0
name:                Module-Find
version:             0.08
version_from:        Find.pm
abstract:            Find and use installed modules in a (sub)category
license:             perl
author:              
    - Christian Renz <crenz@web42.com>
distribution_type:   module
requires:     
    File::Find:                    0
    File::Spec:                    0
    Test::More:                    0
    perl: 5.006001
recommends:
    Test::Pod::Coverage 1.04
build_requires:
    Test::Pod:                     1.14
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.4.html
    version: 1.4
