---
abstract: 'Dynamic definition of a DBIx::Class::Schema'
author:
  - 'blblack: Brandon Black <blblack@gmail.com>'
build_requires:
  DBD::SQLite: 1.12
  DBI: 1.56
  ExtUtils::MakeMaker: 6.42
  File::Copy: 0
  File::Path: 2.07
  File::Temp: 0.16
  IPC::Open3: 0
  List::MoreUtils: 0
  Test::Exception: 0
  Test::More: 0.94
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 0.93'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: DBIx-Class-Schema-Loader
no_index:
  directory:
    - inc
    - t
provides:
  DBIx::Class::Schema::Loader:
    file: lib/DBIx/Class/Schema/Loader.pm
    version: 0.05003
  DBIx::Class::Schema::Loader::Base:
    file: lib/DBIx/Class/Schema/Loader/Base.pm
    version: 0.05003
  DBIx::Class::Schema::Loader::DBI:
    file: lib/DBIx/Class/Schema/Loader/DBI.pm
    version: 0.05003
  DBIx::Class::Schema::Loader::DBI::Component::QuotedDefault:
    file: lib/DBIx/Class/Schema/Loader/DBI/Component/QuotedDefault.pm
    version: 0.05003
  DBIx::Class::Schema::Loader::DBI::DB2:
    file: lib/DBIx/Class/Schema/Loader/DBI/DB2.pm
    version: 0.05003
  DBIx::Class::Schema::Loader::DBI::MSSQL:
    file: lib/DBIx/Class/Schema/Loader/DBI/MSSQL.pm
    version: 0.05003
  DBIx::Class::Schema::Loader::DBI::ODBC:
    file: lib/DBIx/Class/Schema/Loader/DBI/ODBC.pm
    version: 0.05003
  DBIx::Class::Schema::Loader::DBI::ODBC::Microsoft_SQL_Server:
    file: lib/DBIx/Class/Schema/Loader/DBI/ODBC/Microsoft_SQL_Server.pm
    version: 0.05003
  DBIx::Class::Schema::Loader::DBI::ODBC::SQL_Anywhere:
    file: lib/DBIx/Class/Schema/Loader/DBI/ODBC/SQL_Anywhere.pm
    version: 0.05003
  DBIx::Class::Schema::Loader::DBI::Oracle:
    file: lib/DBIx/Class/Schema/Loader/DBI/Oracle.pm
    version: 0.05003
  DBIx::Class::Schema::Loader::DBI::Pg:
    file: lib/DBIx/Class/Schema/Loader/DBI/Pg.pm
    version: 0.05003
  DBIx::Class::Schema::Loader::DBI::SQLAnywhere:
    file: lib/DBIx/Class/Schema/Loader/DBI/SQLAnywhere.pm
    version: 0.05003
  DBIx::Class::Schema::Loader::DBI::SQLite:
    file: lib/DBIx/Class/Schema/Loader/DBI/SQLite.pm
    version: 0.05003
  DBIx::Class::Schema::Loader::DBI::Sybase:
    file: lib/DBIx/Class/Schema/Loader/DBI/Sybase.pm
    version: 0.05003
  DBIx::Class::Schema::Loader::DBI::Sybase::Common:
    file: lib/DBIx/Class/Schema/Loader/DBI/Sybase/Common.pm
    version: 0.05003
  DBIx::Class::Schema::Loader::DBI::Sybase::Microsoft_SQL_Server:
    file: lib/DBIx/Class/Schema/Loader/DBI/Sybase/Microsoft_SQL_Server.pm
    version: 0.05003
  DBIx::Class::Schema::Loader::DBI::Writing:
    file: lib/DBIx/Class/Schema/Loader/DBI/Writing.pm
    version: 0.05003
  DBIx::Class::Schema::Loader::DBI::mysql:
    file: lib/DBIx/Class/Schema/Loader/DBI/mysql.pm
    version: 0.05003
  DBIx::Class::Schema::Loader::RelBuilder:
    file: lib/DBIx/Class/Schema/Loader/RelBuilder.pm
    version: 0.05003
  DBIx::Class::Schema::Loader::RelBuilder::Compat::v0_040:
    file: lib/DBIx/Class/Schema/Loader/RelBuilder/Compat/v0_040.pm
requires:
  Carp::Clan: 0
  Class::Accessor::Grouped: 0.09002
  Class::C3: 0.18
  Class::C3::Componentised: 1.0005
  Class::Inspector: 0
  Class::Unload: 0
  DBIx::Class: 0.08114
  Data::Dump: 1.06
  Digest::MD5: 2.36
  File::Slurp: 9999.13
  File::Spec: 0
  Lingua::EN::Inflect::Number: 1.1
  List::MoreUtils: 0
  Scalar::Util: 0
  Text::Balanced: 0
  namespace::autoclean: 0
resources:
  IRC: irc://irc.perl.org/#dbix-class
  MailingList: http://lists.scsys.co.uk/cgi-bin/mailman/listinfo/dbix-class
  license: http://dev.perl.org/licenses/
  repository: git://git.shadowcat.co.uk/dbsrgits/DBIx-Class-Schema-Loader.git
version: 0.05003
