---
abstract: 'Perl extension for generating Globally/Universally '
author:
  - 'Ricardo Signes <rjbs[at]cpan.org>'
build_requires:
  ExtUtils::MakeMaker: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.6302, CPAN::Meta::Converter version 2.120921'
license: bsd
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Data-UUID
no_index:
  directory:
    - t
    - inc
requires:
  Digest::MD5: 0
version: 1.218
