---
name: Test-Exception
version: 0.24
author:
  - 'Adrian Howard <adrianh@quietstars.com>'
abstract: Test exception based code
license: perl
resources:
  license: http://dev.perl.org/licenses/
requires:
  Sub::Uplevel: 0.13
  Test::Builder: 0.33
  Test::Builder::Tester: 1.04
  Test::Harness: 2.03
  Test::More: 0.44
  perl: 5.6.1
provides:
  Test::Exception:
    file: lib/Test/Exception.pm
    version: 0.24
generated_by: Module::Build version 0.2805
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
