
no_index: 
  directory: 
    - inc
    - t
generated_by: Module::Install version 0.62
distribution_type: module
version: 1.16
name: Class-Inspector
author: Adam Kennedy <cpan@ali.as>
license: perl
build_requires: 
  Test::More: 0.47
requires: 
  perl: 5.005
  File::Spec: 0.80
abstract: Get information about a class and its structure
