abstract: Convert between perl data structures and ASN.1 encoded packets
author: 'Graham Barr <gbarr@cpan.org>'
distribution_type: module
generated_by: Module::Install version 0.64
license: perl
name: Convert-ASN1
no_index:
  directory:
    - inc
    - t
requires:
  perl: 5.005
version: 0.21
