---
abstract: 'Extensible and flexible object <-> relational mapper.'
author:
  - 'mst: Matt S. Trout <mst@shadowcatsystems.co.uk>'
build_requires:
  DBD::SQLite: 1.25
  File::Temp: 0.22
  Test::Builder: 0.33
  Test::Exception: 0
  Test::More: 0.92
  Test::Warn: 0.21
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 0.93'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: DBIx-Class
no_index:
  directory:
    - examples
    - inc
    - lib/DBIx/Class/Admin
    - lib/DBIx/Class/CDBICompat
    - lib/DBIx/Class/PK/Auto
    - lib/DBIx/Class/SQLAHacks
    - t
  package:
    - DBIx::Class::SQLAHacks
    - DBIx::Class::Storage::DBIHacks
requires:
  Carp::Clan: 6.0
  Class::Accessor::Grouped: 0.09002
  Class::C3::Componentised: 1.0005
  Class::Inspector: 1.24
  Context::Preserve: 0.01
  DBI: 1.609
  Data::Dumper::Concise: 1.000
  Data::Page: 2.00
  MRO::Compat: 0.09
  Module::Find: 0.06
  Path::Class: 0.18
  SQL::Abstract: 1.61
  SQL::Abstract::Limit: 0.13
  Scope::Guard: 0.03
  Sub::Name: 0.04
  perl: 5.8.1
resources:
  IRC: irc://irc.perl.org/#dbix-class
  MailingList: http://lists.scsys.co.uk/cgi-bin/mailman/listinfo/dbix-class
  license: http://dev.perl.org/licenses/
  repository: http://dev.catalyst.perl.org/repos/bast/DBIx-Class/
version: 0.08120
