---
name: DBIx-Class
version: 0.07005
author:
  - 'mst: Matt S. Trout <mst@shadowcatsystems.co.uk>'
abstract: Extensible and flexible object <-> relational mapper.
license: perl
resources:
  license: http://dev.perl.org/licenses/
requires:
  Carp::Clan: 0
  Class::C3: 0.13
  Class::Data::Accessor: 0.01
  Class::Inspector: 0
  Cwd: 3.19
  DBI: 1.4
  Data::Page: 2
  Module::Find: 0
  SQL::Abstract: 1.2
  SQL::Abstract::Limit: 0.101
  Scalar::Util: 0
  Storable: 0
build_requires:
  DBD::SQLite: 1.11
provides:
  DBIC::SQL::Abstract:
    file: lib/DBIx/Class/Storage/DBI.pm
  DBIx::Class:
    file: lib/DBIx/Class.pm
    version: 0.07005
  DBIx::Class::AccessorGroup:
    file: lib/DBIx/Class/AccessorGroup.pm
  DBIx::Class::CDBICompat:
    file: lib/DBIx/Class/CDBICompat.pm
  DBIx::Class::CDBICompat::ColumnGroups::GrouperShim:
    file: lib/DBIx/Class/CDBICompat/ColumnGroups.pm
  DBIx::Class::Core:
    file: lib/DBIx/Class/Core.pm
  DBIx::Class::Cursor:
    file: lib/DBIx/Class/Cursor.pm
  DBIx::Class::DB:
    file: lib/DBIx/Class/DB.pm
  DBIx::Class::InflateColumn:
    file: lib/DBIx/Class/InflateColumn.pm
  DBIx::Class::InflateColumn::DateTime:
    file: lib/DBIx/Class/InflateColumn/DateTime.pm
  DBIx::Class::Ordered:
    file: lib/DBIx/Class/Ordered.pm
  DBIx::Class::PK:
    file: lib/DBIx/Class/PK.pm
  DBIx::Class::PK::Auto:
    file: lib/DBIx/Class/PK/Auto.pm
  DBIx::Class::Relationship:
    file: lib/DBIx/Class/Relationship.pm
  DBIx::Class::Relationship::Base:
    file: lib/DBIx/Class/Relationship/Base.pm
  DBIx::Class::ResultSet:
    file: lib/DBIx/Class/ResultSet.pm
  DBIx::Class::ResultSetColumn:
    file: lib/DBIx/Class/ResultSetColumn.pm
  DBIx::Class::ResultSetManager:
    file: lib/DBIx/Class/ResultSetManager.pm
  DBIx::Class::ResultSource:
    file: lib/DBIx/Class/ResultSource.pm
  DBIx::Class::ResultSource::Table:
    file: lib/DBIx/Class/ResultSource/Table.pm
  DBIx::Class::ResultSourceProxy::Table:
    file: lib/DBIx/Class/ResultSourceProxy/Table.pm
  DBIx::Class::Row:
    file: lib/DBIx/Class/Row.pm
  DBIx::Class::Schema:
    file: lib/DBIx/Class/Schema.pm
  DBIx::Class::Serialize::Storable:
    file: lib/DBIx/Class/Serialize/Storable.pm
  DBIx::Class::Storage::DBI:
    file: lib/DBIx/Class/Storage/DBI.pm
  DBIx::Class::Storage::DBI::Cursor:
    file: lib/DBIx/Class/Storage/DBI/Cursor.pm
  DBIx::Class::Storage::DBI::DB2:
    file: lib/DBIx/Class/Storage/DBI/DB2.pm
  DBIx::Class::Storage::DBI::MSSQL:
    file: lib/DBIx/Class/Storage/DBI/MSSQL.pm
  DBIx::Class::Storage::DBI::MultiDistinctEmulation:
    file: lib/DBIx/Class/Storage/DBI/MultiDistinctEmulation.pm
  DBIx::Class::Storage::DBI::NoBindVars:
    file: lib/DBIx/Class/Storage/DBI/NoBindVars.pm
  DBIx::Class::Storage::DBI::ODBC:
    file: lib/DBIx/Class/Storage/DBI/ODBC.pm
  DBIx::Class::Storage::DBI::ODBC::DB2_400_SQL:
    file: lib/DBIx/Class/Storage/DBI/ODBC/DB2_400_SQL.pm
  DBIx::Class::Storage::DBI::Oracle:
    file: lib/DBIx/Class/Storage/DBI/Oracle.pm
  DBIx::Class::Storage::DBI::Pg:
    file: lib/DBIx/Class/Storage/DBI/Pg.pm
  DBIx::Class::Storage::DBI::SQLite:
    file: lib/DBIx/Class/Storage/DBI/SQLite.pm
  DBIx::Class::Storage::DBI::Sybase:
    file: lib/DBIx/Class/Storage/DBI/Sybase.pm
  DBIx::Class::Storage::DBI::Sybase::MSSQL:
    file: lib/DBIx/Class/Storage/DBI/Sybase/MSSQL.pm
  DBIx::Class::Storage::DBI::mysql:
    file: lib/DBIx/Class/Storage/DBI/mysql.pm
  DBIx::Class::Storage::NESTED_ROLLBACK_EXCEPTION:
    file: lib/DBIx/Class/Storage.pm
  DBIx::Class::Storage::Statistics:
    file: lib/DBIx/Class/Storage/Statistics.pm
  DBIx::Class::Test::SQLite:
    file: lib/DBIx/Class/Test/SQLite.pm
  DBIx::Class::UTF8Columns:
    file: lib/DBIx/Class/UTF8Columns.pm
  DBIx::ContextualFetch::st:
    file: lib/DBIx/Class/CDBICompat/ImaDBI.pm
  SQL::Translator::Producer::DBIx::Class::File:
    file: lib/SQL/Translator/Producer/DBIx/Class/File.pm
    version: 0.1
generated_by: Module::Build version 0.28
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
