--- 
abstract: Wrapper Class for the various JSON classes.
author: 
  - Chris Thompson, C<< <cthom at cpan.org> >>
build_requires: 
  Test::More: 0
distribution_type: module
generated_by: Module::Install version 0.68
license: perl
meta-spec: 
  url: http://module-build.sourceforge.net/META-spec-v1.3.html
  version: 1.3
name: JSON-Any
no_index: 
  directory: 
    - ex
    - inc
    - t
requires: 
  Carp: 0
version: 1.16
